apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: $registry:$BUILD_NUMBER
        ports:
        - containerPort: 3000