# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

containerPort: 80

image:
  repository: watri/website:latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  protocol: TCP
  port: 80
  targetPort: 3000
